// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohkgjuphudlnbwiqrfsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oa2dqdXBodWRsbmJ3aXFyZnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDQzMDEsImV4cCI6MjA2NDEyMDMwMX0.CWp86rSb8xPzXg7y5uTGnrFyMiN1NqLFmh-Z15tND-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);